import { InventaireInterface } from "../interfaces/InventaireInterface";

const inventaireData: InventaireInterface[] = [
  {
    section: "Confort",
    items: [
      "1 Air conditionné fixe (avec la télécommande)",
      "1 Air conditionné mobile Amcor (et deux tuyaux)",
    ],
  },
  {
    section: "Coin Cuisine",
    items: [
      "1 Taque de cuisson au gaz avec 4 becs sur armoire roulante + Bonbonne",
      "1 Congélateur frigo Edesa avec 3 blocs glaçons et 2bac à glaçons",
      "1 Lave vaisselle Zanusi",
      "1 Radio Maniway CD, MP3,USB + télécommande sur étagère",
      "6 Planches en bois avec support et machine à café",
      "1 Poubelle inox",
      "6 Planches à tartine en PVC",
    ],
  },
  {
    section: "Salle à manger",
    items: [
      "1 Bahut 2 pièces style castillan",
      "1 Table 1m 60 + toile cirée + 6 Chaises de paille",
      "1 TV AKAI 22 ''ALED2205TBK avec lect. DVD, tuner DVB- T intégré + télécommande, avec prise interrupteur. 1 câble HDMI de 3 m.",
      "1 Réveil vert",
      "1 Table de jardin ovale, blanche 0,9m/1,4m (les pieds se retirent)",
      "6 Chaises plastiques vertes de jardin",
      "1 Séchoir métallique Tancarville",
      "1 Parasol + Pied pour parasol (sur terrasse)",
      "1 Set de cordes à linge à dérouler sur Terrasse",
      "1 Divan-lit 2 personnes",
      "2 Coussins",
      "2 Sièges pliables",
      "2 Sièges relax",
      "1 Grille barbecue avec pinces; autres grilles",
      "2 Tentures brunes",
      "1 Anti insectes électrique",
      "1 Ventilateur plafonnier et lampe",
      "2 Allonges électriques +2 Dominos électr.",
      "1 Planche à repasser",
      "1 Aspirateur type cyclonique sans sac",
    ],
  },
  {
    section: "Chambre rez-de-chaussée",
    items: [
      "2 lits superposés (90x190 cm)",
      "2 Sommiers",
      "2 Matelas",
      "2 protèges matelas",
      "3 Couvres lits",
      "3 Oreillers",
      "1 Ventilateur plafonnier et lampe de chevet",
      "1 Bac PVC de rangement avec 2 couvertures",
      "1 Porte de sécurité escalier pour enfant",
      "1 Armoire double porte",
      "1 Etagère table de nuit (5 étages)",
      '1 Porte "enfant" démontable',
      "1 Porte manteau",
      "1 lit (90 x 190cm) avec matelas et sommier",
      "1 protège matelas",
    ],
  },
  {
    section: "Salle de bain rez-de-chaussée",
    items: [
      "1 Rideau de douche",
      "1 Armoire (glace)",
      "1 Brosse à long manche",
      "1 Petite poubelle",
      "1 Machine à laver « ZANUSSI »",
      "1 Brosse WC",
      "2 Brosses à balayer + 1 Raclette + 1 Brosse extensive à poussière",
      "1 Nécessaire à laver espagnol + 1 seau",
      "1 Bassin à lessive et une manne",
    ],
  },
  {
    section: "Chambre à coucher 1er étage",
    items: [
      "Meuble réservé au propriétaire (sur le palier)",
      "1 Lit de 140 cm avec matelas de type « épéda »",
      "1 Protège matelas",
      "1 Tête de lit de 1m40 de style castillan",
      "1 Couvre lit",
      "2 Oreillers",
      "2 Tables de nuit",
      "2 Lampes de chevet",
      "7 Cintres + T 3 prises",
      "1 Ventilateur sur pied 40cm",
      "1 Climatiseur Amcor sur roulettes avec 2 tuyaux",
      "1 Bac PVC de rangement avec 2 couvertures",
    ],
  },
  {
    section: "Salle de bain 1er étage",
    items: [
      "1 Armoire à glace (3 lampes)",
      "1 Brosse à WC",
      "1 Petite poubelle",
      "1 Petit meuble 2 tiroirs",
      "1 Rideau de douche",
      "1 Tabouret escabelle",
    ],
  },
  {
    section: "Cuisine et salle à manger",
    items: [
      "Armoire au-dessus de l’évier",
      "Armoire haute à gauche de l’évier",
      "Armoire haute coin",
      "Armoire haute à gauche de la hotte",
      "Armoire basse sous la taque de cuisson",
      "Armoire basse à gauche de la taque de cuisson",
      "Armoire sous évier",
      "31 d’assiettes : plates (17) et creuses (14)",
      "4 Plats blancs 3 Plats Inox",
      "1 Bol mixer manuel",
      "2 Passoires plastiques",
      "1 Services à café (6 pièces)",
      "1 Bols à soupe",
      "6 tasses hautes",
      "1 Presse fruit",
      "1 Cafetière électrique",
      "6 Pots à dessert",
      "1 Filtre à café",
      "6 Cocotiers",
      "1 Salière",
      "1 Poivrière",
      "Des épices",
      "8 verres à vin sur pied",
      "10 verres à bière",
      "1 paire de ciseaux verts",
      "18 Verres",
      "1 Seau à glace",
      "2 casse noix",
      "1 Plat en verre",
      "1 Carafe à eau Ricard",
      "1 Entonnoir",
      "22 Cuillères à soupes",
      "19 Cuillères à café",
      "24 Fourchettes",
      "22 Couteaux",
      "2 Petits couteaux",
      "1 Couteau à pain",
      "4 Grands couteaux",
      "6 Pics à brochettes",
      "3 Spatules en bois",
      "1 Cuillère et 1 Fourchette en bois",
      "1 Couvert à salade en bois",
      "1 Tire-Bouchon décapsuleur",
      "1 fouet",
      "1 Eplucheur à pomme de terre",
      "5 Casseroles (petite, moyenne et grande)",
      "1 Planche en PVC",
      "4 Poêlons (petit, moyen et grand)",
      "5 Poêles",
      "2 plats en PVC",
      "1 Essoreuse salade",
      "2 Sous plats",
      "2 Maniques",
      "3 paniers en osier",
      "1 Seau de 5 Litres",
      "1 seau de 10L",
      "3 Eponges",
      "1 Ramasse poussière",
      "1 Petite brosse",
      "1 égouttoir",
      "1 Tapettes à mouches",
      "1 Regulator (« butano »)",
      "+/-40 Pinces à linge",
    ],
  },
  {
    section: "Bahut",
    items: [
      "1 Louche",
      "1 Ouvre boite",
      "1 Tire-bouchon",
      "1 Pince barbecue",
      "1 Pince à spaghettis",
      "1 Pince à sucre",
      "1 Pelle à tarte",
      "1 Bouche bouteille",
      "2 Plats en plastique",
      "2 Râpe carottes",
      "1 Décapsuleur",
      "2 Petites passoires",
    ],
  },
  {
    section: "Divers",
    items: [
      "Manuels d'emploi des appareils",
      "Clé de la porte de la chambre du rez de chaussée",
      "Clé de la maison et de la porte vitrée",
      "1 Plateau de service",
      "1 Fer à repasser",
      "2 Draps pour le piquenique",
      "1 Regata",
      "1 Livre d'or",
    ],
  },
];
export default inventaireData;
